ViewComponentLesson/Entities/Category.cs
namespace ViewComponentLesson.Entities;

public class Category
{
    public int Id { get; set; }
    public string Title{ get; set; }

}

ViewComponentLesson/Entities/Product.cs
namespace ViewComponentLesson.Entities;

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public decimal Price { get; set; }
}

ViewComponentLesson/Models/CategoryListViewModel.cs
using ViewComponentLesson.Entities;

namespace ViewComponentLesson
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
    }
}

ViewComponentLesson/Models/ErrorViewModel.cs
namespace ViewComponentLesson.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ViewComponentLesson/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ViewComponentLesson.Areas.Admin.Controllers;
public class HomeController : Controller
{
    [Area("admin")]
    public IActionResult Index()
    {
        return View();
    }
}

ViewComponentLesson/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentLesson.Context;

namespace ViewComponentLesson.Controllers
{
    public class HomeController(AppDbContext _context) : Controller
    {
        public IActionResult Index() => View();

        public IActionResult Categories() => Json(_context.Categories);
    }
}

ViewComponentLesson/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ViewComponentLesson.Context;
using ViewComponentLesson.Entities;

namespace ViewComponentLesson.Pages;

public class IndexModel(AppDbContext context) : PageModel
{
    private readonly AppDbContext _context = context;
    public string Message { get; set; }
    public string Info { get; set; }
    public List<Product> Products { get; set; }

    [BindProperty]
    public Product Product { get; set; }
    public void OnGet()
    {
        Products = _context.Products.ToList();

    }
    public IActionResult OnPost( )
    {

        if (Product.Id == 0)
        {

            _context.Products.Add(Product);
            _context.SaveChanges();
            Message = $"{Product.Name} Added successfully";
        }
        else
        {
            _context.Products.Update(Product);
            _context.SaveChanges();
            Message = $"{Product.Name} Updated successfully";
        }
        Product = new Product();
        return RedirectToPage("Index");
    }



    public async Task<IActionResult> OnPostDeleteAsync(int id)
    {
        var product = await _context.Products.FirstOrDefaultAsync(x => x.Id == id);
        _context.Products.Remove(product!);
        await _context.SaveChangesAsync();
        Message = $"{product?.Name} Deleted successfully";
        return RedirectToPage("Index");
    }

    public IActionResult OnPostUpdate(int id)
    {
        Product = _context.Products.FirstOrDefault(x => x.Id == id)!;
        Product.Id = id;
        Products = _context.Products.ToList();
        return Page();
    }

}

ViewComponentLesson/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using ViewComponentLesson.Context;
using ViewComponentLesson.Entities;

namespace ViewComponentLesson.ViewComponents
{
    public class CategoryListViewComponent(AppDbContext context) : ViewComponent
    {
        private readonly AppDbContext _context = context;
        public ViewViewComponentResult Invoke()
        {
            return View(new CategoryListViewModel
            {
                Categories=_context.Categories.ToList(),

            });
        }
    }
}

ViewComponentLesson/Areas/Admin/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section>
    <h2>Hello Admin Module</h2>
    <hr style="border-color:lawngreen;"/>
</section>

ViewComponentLesson/Areas/Admin/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

ViewComponentLesson/Pages/Index.cshtml
@page
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model ViewComponentLesson.Pages.IndexModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="m-5 text-danger">Special Info @Model.Message</h1>




<table class="table">
    <thead>
        <tr>
            <th class="col">Id</th>
            <th class="col">Name</th>
            <th class="col">Price</th>
            <th class="col">Edit</th>
            <th class="col">
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model?.Products)
        {
            <tr>
                <th class="col">@item.Id</th>
                <th class="col">@item.Name</th>
                <th class="col">@item.Price</th>
                <th class="col">
                    <form method="post" asp-page-handler="Update">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </form>
                </th>

                <th class="col">
                    <form method="post" asp-page-handler="Delete">
                        <input type="hidden" name="id" value="@item.Id" />
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </th>

            </tr>
        }
    </tbody>

    <form class="col-5 gap-3" method="post" asp-page-handler="" asp-route-id="Product.Id">
        <div class="wb-3 gap-3">
            <label class="from-label" asp-for="Product.Id"></label>
            <input readonly type="text" class="form-control" asp-for="Product.Id" />
        </div>
        <div class="wb-3 gap-3">
            <label class="from-label" asp-for="Product.Name"></label>
            <input type="text" class="form-control" asp-for="Product.Name" />
        </div>
        <div class="wb-3 gap-3 my-3">
            <label class="from-label" asp-for="Product.Price"></label>
            <input asp-for="Product.Price" type="number" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</table>

ViewComponentLesson/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ViewComponentLesson/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel

<section>
    <h1>Categories</h1>
    <ul class="list-group">
        @foreach (var category in Model.Categories)
        {
            <li class="list-group-item">@category.Title</li>
        }
    </ul>
</section>

ViewComponentLesson/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ViewComponentLesson</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ViewComponentLesson.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ViewComponentLesson</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <div class="row">
            <div class="col-2">
                @await Component.InvokeAsync("CategoryList")
            </div>
            <div class="col-10">

                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ViewComponentLesson - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>